spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://localhost:5432/stockmanagementdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8081

flickr:
  apiKey: 681d846e029ce63875f4296a0fdfcd95
  apiSecret: 3c5d4890755b348e
  appKey: 72157720906167037-d07ceb641d8113e0
  appSecret: d81d72e1c1f5328a

